In [ ]:
!unzip /content/trainset.zip

In [ ]:
!unzip /content/devtestset.zip

In [ ]:
try:
    import xml.etree.cElementTree as ET
except ImportError:
    import xml.etree.ElementTree as ET

In [ ]:
import xml.etree.cElementTree as ET
tree = ET.ElementTree(file='/content/trainset/114354.xml')

In [ ]:
tree.getroot()

<Element 'pubmedarticleset' at 0x7fcbd79dd590>

In [ ]:
root = tree.getroot()
root.tag,root.attrib

('pubmedarticleset', {})

In [ ]:
for child_of_root in root:
  print(child_of_root.tag, child_of_root.attrib)

pubmedarticle {}


In [ ]:
for elem in tree.iter(tag="descriptorname"):
  print(elem.tag,elem.attrib)

In [ ]:
for msh in tree.findall('meshheading'):
  print(msh)

In [ ]:
print(tree.findall("./pubmedarticle"))

[<Element 'pubmedarticleset' at 0x7fcbd7ce5d10>]


In [ ]:
for elem in tree.findall("./pubmedarticle/medlinecitation/meshheadinglist/meshheading"):
  print(elem.tag,elem.attrib)

In [ ]:
for elem in tree.findall(".//meshheading/qualifiername[@majortopicyn='Y']"):
  print(elem.tag,elem.attrib,elem.text)

In [ ]:
import xml.etree.cElementTree as ET
import os

#path = "/content/trainset"
path1 = "/content/train.txt"

#for f in os.listdir(path):
with open(path1, 'w') as wf:
    #path2 = path + "/" + f
  tree = ET.ElementTree(file="/content/trainset/12873166.xml")
    #print(path2)
    #print(f[:-4])
  wf.write("12873166")
  for elem in tree.findall(".//meshheading"):
      tag = 0
      qualif = []
      for elem1 in elem.findall("./descriptorname"):
        YorN = elem1.get('majortopicyn')
        if(YorN=="N"):
          #print(elem1.tag,elem1.attrib,elem1.text)
          #print("++++++++++")
          tag+=1
        elif(YorN=="Y"):
          tag=100
      for elem2 in elem.findall("./qualifiername"):
        YorN2 = elem2.get('majortopicyn')
        if(YorN2=="Y"):
          #print(elem2.tag,elem2.attrib,elem2.text)
          tag+=1
          qualif.append(str(elem2.text).strip("\n").strip(" ").strip("\t"))
      if(100>tag>=2):
        #print(elem1.text,elem2.text)
        #print("------------")
        elem1_str = str(elem1.text).strip("\n").strip(" ").strip("\t")
        elem2_str = str(elem2.text).strip("\n").strip(" ").strip("\t")
        wf.write("\t" + "{[" + elem1_str + "]")
        for qq in qualif:
          print(qq)
          wf.write("," + "[" + qq + "]")
        wf.write("}")
      if(tag==100):
        #print(elem1.text)
        elem1_str = str(elem1.text).strip("\n").strip(" ")
        wf.write("\t" + "{[" + elem1_str  + "]}")
        #print("++++++++++++")
  wf.write("\n")
      #print("++++++++++++++++++++++++")

pathology

virology

pathology

virology

pathology

virology

pathology

virology



In [ ]:
for elem in tree.findall('descriptorname[@majortopicyn="N"]'):
  print(elem.tag, elem.attrib)

In [ ]:
from xml.dom.minidom import parse
import xml.dom.minidom

DOMTree = xml.dom.minidom.parse("/content/trainset/10023943.xml")
collection = DOMTree.documentElement

movies = collection.getElementsByTagName("meshheading")

for movie in movies:
   print (movie)
   #type11 = movie.getElementsByTagName('descriptorname')[0]
   #print(type11.childNodes[0].data)
   #type22 = movie.getElementsByTagName('qualifiername')

In [ ]:
if collection.hasAttribute("shelf"):
   print ("Root element : %s" % collection.getAttribute("shelf"))

# 在集合中获取所有电影
movies = collection.getElementsByTagName("movie")

# 打印每部电影的详细信息
for movie in movies:
   print ("*****Movie*****")
   if movie.hasAttribute("title"):
      print ("Title: %s" % movie.getAttribute("title"))

   type = movie.getElementsByTagName('type')[0]
   print ("Type: %s" % type.childNodes[0].data)
   format = movie.getElementsByTagName('format')[0]
   print ("Format: %s" % format.childNodes[0].data)
   rating = movie.getElementsByTagName('rating')[0]
   print ("Rating: %s" % rating.childNodes[0].data)
   description = movie.getElementsByTagName('description')[0]
   print ("Description: %s" % description.childNodes[0].data)

In [ ]:
#path = "/content/trainset.txt"
#path1 = "/content/train.txt"
#path2 = "/content/train_new.txt"
path = "/content/devtestset.txt"
path1 = "/content/dev.txt"
path2 = "/content/dev_new.txt"


with open(path, "r") as f:
  with open(path1,"r") as f1:
    with open(path2,"a") as wf:
      text = f.readlines()
      text1 = f1.readlines()
      for line in text:
        new_line = line.strip("\n").split(" ")
        #print(new_line)
        length = len(new_line)
        wf.write(new_line[0] + " " + new_line[1] + " ")
        #print(length)
        for i in range(2,length):
          #print(new_line[i])
          f1.seek(0)
          for line1 in text1:
            new_line1 = line1.strip("\n").split("\t")
            if(new_line[i]==new_line1[0]):
              #print(new_line1)
              for k in range(len(new_line1)):
                wf.write(new_line1[k] + " ")
        wf.write("\n")


把descriptorname/abstract作为feature

In [ ]:
path = "/content/trainset.txt"
path1 = "/content/train_abs.txt"
path2 = "/content/train_abs_new.txt"
#path = "/content/devtestset.txt"
#path1 = "/content/dev_abs.txt"
#path2 = "/content/dev_abs_new.txt"


with open(path, "r") as f:
  with open(path1,"r") as f1:
    with open(path2,"a") as wf:
      text = f.readlines()
      text1 = f1.readlines()
      for line in text:
        new_line = line.strip("\n").split(" ")
        #print(new_line)
        length = len(new_line)
        wf.write(new_line[1] + "\t")
        #print(length)
        for i in range(2,length):
          #print(new_line[i])
          f1.seek(0)
          for line1 in text1:
            new_line1 = line1.strip("\n").split("\t")
            if(new_line[i]==new_line1[0]):
              #print(new_line1)
              for k in range(1,len(new_line1)):
                wf.write(new_line1[k] + " ")
        wf.write("\n")


In [ ]:
path = "/content/train_abs_new.txt"
path1 = "/content/train_abs_new1.txt"

with open(path,"r") as f:
  with open(path1,"a") as wf:
    text = f.readlines()
    for line in text:
      #print(line)
      new_line = line.strip("\n").split("\t")
      #print(new_line)
      wf.write(new_line[1] + "\t" + new_line[0] + "\n")

In [ ]:
import csv

txt_file = "/content/train_abs_new1.txt"
csv_file = "/content/train_abs_new2.csv"

in_txt = csv.reader(open(txt_file,"r"), delimiter = '\t')
out_csv = csv.writer(open(csv_file, 'w'))

out_csv.writerow(["text","label"])
out_csv.writerows(in_txt)

abstract

In [ ]:
import xml.etree.cElementTree as ET
import os

path = "/content/trainset"
path1 = "/content/train_abs.txt"
#path = "/content/devtestset"
#path1 = "/content/dev_abs.txt"

for f in os.listdir(path):
  with open(path1, 'a') as wf:
    #path2 = path + "/" + f
    tree = ET.ElementTree(file=path + "/" + f)
    #print(path2)
    #print(f[:-4])
    wf.write(f[:-4] + "\t")
    for elem in tree.findall(".//abstract"):
      #print(elem)
      tag = 0
      qualif = []
      for elem1 in elem.findall("./abstracttext"):
        #print(elem1.text)
        string = str(elem1.text).strip("\n").replace("\n"," ")
        print(string)
        wf.write(string + " ")
    wf.write("\n")

单篇单篇的

In [ ]:
#path = "/content/devtestset.txt"
#path1 = "/content/devtestset1.txt"
path = "/content/trainset.txt"
path1 = "/content/trainset1.txt"

with open(path,"r") as f:
  with open(path1,"a") as wf:
    text = f.readlines()
    for line in text:
      new_line = line.strip("\n").split(" ")
      #print(new_line)
      for i in range(len(new_line)-2):
        wf.write(new_line[1] + " " + new_line[2+i] + "\n")

In [ ]:
path = "/content/trainset1.txt"
path1 = "/content/train_abs.txt"
path2 = "/content/train_abs_per.txt"
#path = "/content/devtestset1.txt"
#path1 = "/content/dev_abs.txt"
#path2 = "/content/dev_abs_per.txt"


with open(path, "r") as f:
  with open(path1,"r") as f1:
    with open(path2,"a") as wf:
      text = f.readlines()
      text1 = f1.readlines()
      for line in text:
        new_line = line.strip("\n").split(" ")
        #print(new_line)
        wf.write(new_line[0] + "\t")
        f1.seek(0)
        for line1 in text1:
          new_line1 = line1.strip("\n").split("\t")
          if(new_line[1]==new_line1[0]):
              for k in range(1,len(new_line1)):
                wf.write(new_line1[k] + " ")
        wf.write("\n")

In [ ]:
path = "/content/train_abs_per.txt"
path1 = "/content/train_abs_per1.txt"
#path = "/content/dev_abs_per.txt"
#path1 = "/content/dev_abs_per1.txt"

with open(path,"r") as f:
  with open(path1,"a") as wf:
    text = f.readlines()
    for line in text:
      #print(line)
      new_line = line.strip("\n").split("\t")
      #print(new_line)
      wf.write(new_line[1] + "\t" + new_line[0] + "\n")

In [ ]:
import csv

txt_file = "/content/train_abs_per1.txt"
csv_file = "/content/train_abs_per2.csv"
#txt_file = "/content/dev_abs_per1.txt"
#csv_file = "/content/dev_abs_per2.csv"

in_txt = csv.reader(open(txt_file,"r"), delimiter = '\t')
out_csv = csv.writer(open(csv_file, 'w'))

out_csv.writerow(["text","label"])
out_csv.writerows(in_txt)

根据preds的embedding求average，然后再找最大max，再求accuracy


In [ ]:
path = "/content/devtestset1.txt"
path1 = "/content/dev_preds_embedding.txt"

with open(path, "r") as f:
  with open(path1, "r") as f1:
    text = f.readlines()
    text1 = f1.readlines()

    #print(len(text))
    #print(len(text1))
    for i in range(len(text)):
      line = text[i]
      new_line = line.strip("\n").split(" ")
      line1 = text1[i]
      #print(new_line[1],line1)
      with open("/content/dev_filename_embedding1.txt","a") as wf:
        wf.write(new_line[1]+ "\t" + line1)

求平均

In [ ]:
path = "/content/devtestset.txt"
path1 = "/content/dev_filename_embedding1.txt"
import numpy as np

list_emb = []
with open(path, "r") as f:
  with open(path1,"r") as f1:
    text = f.readlines()
    text1 = f1.readlines()
    for line in text:
      sum = [0.0,0.0,0.0]
      new_line=line.strip("\n").split(" ")
      print(new_line,len(new_line)-2)
      for i in range(len(new_line)-2):
        file = new_line[i+2]
        f1.seek(0)
        for line1 in text1:
          new_line1 = line1.strip("\n").split("\t")
          if(new_line1[0]==file):
            #print(new_line1[1].shape)
            list_str = new_line1[1].replace("   "," ").replace("  "," ").replace("[","").replace(" ]","]").replace("]","").split(' ')
            #print(list_str)
            list2 = []
            for j in list_str:
              list2.append(float(j))
            arr1 = np.array(list2)
            print(arr1)
            sum+=arr1
            break;
      print("sum：", sum/(len(new_line)-2))
      list_emb.append(list(sum/(len(new_line)-2)))

['10001', 'B', '19454119'] 1
[-1.1184708 -1.0961295 -1.0815814]
sum： [-1.1184708 -1.0961295 -1.0815814]
['10002', 'A', '12531578', '11110735'] 2
[-1.080343  -1.0610852 -1.1569594]
[-1.1180962 -1.0945581 -1.0834941]
sum： [-1.0992196  -1.07782165 -1.12022675]
['10003', 'A', '10637680', '11762571', '2254504', '11225739', '12025432', '8951257'] 6
[-1.1112684 -1.0925754 -1.0921123]
[-1.0779349 -1.0524693 -1.1691599]
[-1.1075902 -1.0565486 -1.1332277]
[-1.0842394 -1.0663202 -1.1470631]
[-1.1073375 -1.0904927 -1.0980779]
[-1.0956498 -1.0526689 -1.1498864]
sum： [-1.0973367  -1.06851252 -1.13158788]
['10004', 'A', '9679792'] 1
[-1.1196651 -1.1052309 -1.0715522]
sum： [-1.1196651 -1.1052309 -1.0715522]
['10005', 'C', '6726967', '9651416'] 2
[-1.1203331 -1.0931833 -1.0826969]
[-1.1314439 -1.1063528 -1.059383 ]
sum： [-1.1258885  -1.09976805 -1.07103995]
['10006', 'B', '9402381', '17133159'] 2
[-1.0777191 -1.0582255 -1.1629655]
[-1.0844294 -1.0514826 -1.1631955]
sum： [-1.08107425 -1.05485405 -1.1630

In [ ]:
print(list_emb)

[[-1.1184708, -1.0961295, -1.0815814], [-1.0992196, -1.07782165, -1.12022675], [-1.0973366999999998, -1.0685125166666667, -1.1315878833333333], [-1.1196651, -1.1052309, -1.0715522], [-1.1258885, -1.09976805, -1.0710399499999999], [-1.08107425, -1.0548540499999999, -1.1630805], [-1.0938723, -1.061203, -1.1424274], [-1.0904128499999999, -1.0561193, -1.1516587500000002], [-1.0985648333333333, -1.0741201999999999, -1.1255184666666667], [-1.0615162, -1.0568438, -1.1824784], [-1.1001495000000001, -1.07348935, -1.1229833999999999], [-1.1059994666666666, -1.0794494666666667, -1.1108190999999998], [-1.1146964, -1.1001214, -1.0812993], [-1.1131560999999999, -1.0837766, -1.0999319], [-1.090605, -1.0723905, -1.134464275], [-1.1046321, -1.0783129, -1.113928], [-1.1031916, -1.0662879, -1.1273035], [-1.117835, -1.0931848, -1.0851071], [-1.0980986666666666, -1.0699143555555555, -1.1294512], [-1.0896325500000001, -1.08583955, -1.12077115], [-1.09440604, -1.08270456, -1.119607], [-1.0922585, -1.0598476,

In [ ]:

arr3 = np.array(list_emb)

In [ ]:
print(arr3)

[[-1.1184708  -1.0961295  -1.0815814 ]
 [-1.0992196  -1.07782165 -1.12022675]
 [-1.0973367  -1.06851252 -1.13158788]
 [-1.1196651  -1.1052309  -1.0715522 ]
 [-1.1258885  -1.09976805 -1.07103995]
 [-1.08107425 -1.05485405 -1.1630805 ]
 [-1.0938723  -1.061203   -1.1424274 ]
 [-1.09041285 -1.0561193  -1.15165875]
 [-1.09856483 -1.0741202  -1.12551847]
 [-1.0615162  -1.0568438  -1.1824784 ]
 [-1.1001495  -1.07348935 -1.1229834 ]
 [-1.10599947 -1.07944947 -1.1108191 ]
 [-1.1146964  -1.1001214  -1.0812993 ]
 [-1.1131561  -1.0837766  -1.0999319 ]
 [-1.090605   -1.0723905  -1.13446428]
 [-1.1046321  -1.0783129  -1.113928  ]
 [-1.1031916  -1.0662879  -1.1273035 ]
 [-1.117835   -1.0931848  -1.0851071 ]
 [-1.09809867 -1.06991436 -1.1294512 ]
 [-1.08963255 -1.08583955 -1.12077115]
 [-1.09440604 -1.08270456 -1.119607  ]
 [-1.0922585  -1.0598476  -1.1455992 ]
 [-1.1086934  -1.099408   -1.0878447 ]
 [-1.09849747 -1.06303177 -1.13581483]
 [-1.0977363  -1.08588525 -1.11341185]
 [-1.0980154  -1.0802663 

In [ ]:
preds_new = np.argmax(arr3, axis = 1)
print(preds_new.tolist())

[2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1]


In [ ]:
arrr = [2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2,
        2, 2, 2, 2, 1, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 2, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2,
        0, 0, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 2, 1, 0, 0, 2, 2, 1,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 2, 0, 0, 1, 0]

In [ ]:
print(len(arrr))

178
